<script setup lang="ts">
type ArtifactSummary = {
  id: string
  type: string
  title: string
  datasetId?: string
  chatId?: string
  createdAt: string
  updatedAt: string
}

type DevtoolsArtifactResponse = {
  metadata: ArtifactSummary
  report: {
    content?: string
    truncated?: boolean
  } | null
}

const props = defineProps<{
  initialArtifactId?: string
}>()

const { data, pending: listPending, error: listError, refresh: refreshList } = await useFetch<{ artifacts: ArtifactSummary[] }>(
  '/api/devtools/artifacts',
  { default: () => ({ artifacts: [] }) }
)

const artifacts = computed(() => data.value?.artifacts ?? [])
const selectedId = ref<string>(props.initialArtifactId || '')
const lookupId = ref<string>('')
const detailPending = ref(false)
const detail = ref<DevtoolsArtifactResponse | null>(null)
const detailError = ref<string>('')

watch(() => props.initialArtifactId, (id) => {
  if (id) {
    selectedId.value = id
    void loadArtifact(id)
  }
})

watch(selectedId, (id) => {
  if (id) void loadArtifact(id)
})

async function loadArtifact(id: string) {
  if (!id) return
  detailPending.value = true
  detailError.value = ''
  detail.value = null

  try {
    detail.value = await $fetch<DevtoolsArtifactResponse>(`/api/devtools/artifacts/${id}`)
  } catch (err) {
    detailError.value = err instanceof Error ? err.message : String(err)
  } finally {
    detailPending.value = false
  }
}

function selectArtifact(artifact: ArtifactSummary) {
  selectedId.value = artifact.id
}

function lookupArtifact() {
  const id = lookupId.value.trim()
  if (!id) return
  selectedId.value = id
}

function formatDate(value: string) {
  try {
    return new Intl.DateTimeFormat(undefined, {
      dateStyle: 'medium',
      timeStyle: 'short'
    }).format(new Date(value))
  } catch {
    return value
  }
}

const reportContent = computed(() => detail.value?.report?.content || '')
const isReport = computed(() => detail.value?.metadata?.type === 'report')

const lookupValid = computed(() => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(lookupId.value.trim()))

if (props.initialArtifactId) {
  await loadArtifact(props.initialArtifactId)
}
</script>

<template>
  <div class="space-y-5">
    <div class="flex items-center justify-between gap-3">
      <div>
        <h2 class="text-lg font-semibold text-highlighted">
          Artifacts
        </h2>
        <p class="text-sm text-muted">
          Recent artifacts generated by workflows. Report content is sanitized.
        </p>
      </div>
      <UButton
        icon="i-lucide-refresh-cw"
        label="Refresh"
        color="neutral"
        variant="ghost"
        :loading="listPending"
        @click="() => refreshList()"
      />
    </div>

    <UAlert
      v-if="listError"
      color="error"
      variant="soft"
      icon="i-lucide-circle-alert"
      :description="listError.message"
    />

    <div class="grid gap-4 lg:grid-cols-[20rem_minmax(0,1fr)]">
      <!-- Recent artifacts list -->
      <div class="space-y-3">
        <UCard :ui="{ root: 'bg-default/60', body: 'p-0 sm:p-0' }">
          <div class="flex items-center justify-between border-b border-default px-4 py-3">
            <h3 class="text-sm font-semibold text-highlighted">
              Recent
            </h3>
            <UBadge color="neutral" variant="soft">
              {{ artifacts.length }}
            </UBadge>
          </div>

          <div
            v-if="listPending"
            class="flex items-center gap-2 px-4 py-6 text-sm text-muted"
          >
            <UIcon name="i-lucide-loader-circle" class="size-4 animate-spin" />
            Loading…
          </div>

          <ul
            v-else-if="artifacts.length"
            class="max-h-[28rem] divide-y divide-default overflow-auto"
          >
            <li
              v-for="artifact in artifacts"
              :key="artifact.id"
            >
              <button
                type="button"
                class="flex w-full items-start gap-3 px-4 py-3 text-left transition-colors hover:bg-elevated/60"
                :class="artifact.id === selectedId ? 'bg-primary/10' : ''"
                @click="selectArtifact(artifact)"
              >
                <UIcon
                  :name="artifact.type === 'report' ? 'i-lucide-file-text' : 'i-lucide-file'"
                  class="mt-0.5 size-4 shrink-0 text-muted"
                />
                <div class="min-w-0 flex-1">
                  <p class="truncate text-sm font-medium text-highlighted">
                    {{ artifact.title }}
                  </p>
                  <p class="truncate text-xs text-muted">
                    {{ artifact.type }} · {{ formatDate(artifact.updatedAt) }}
                  </p>
                </div>
              </button>
            </li>
          </ul>

          <div
            v-else
            class="px-4 py-6 text-sm text-muted"
          >
            No artifacts yet. Run a workflow to generate a report.
          </div>
        </UCard>

        <!-- Advanced lookup -->
        <UAccordion
          :items="[{
            label: 'Open by id (advanced)',
            icon: 'i-lucide-search',
            slot: 'lookup'
          }]"
        >
          <template #lookup>
            <div class="space-y-2 px-1 py-2">
              <UInput
                v-model="lookupId"
                placeholder="Artifact uuid"
                icon="i-lucide-hash"
                size="sm"
                @keyup.enter="lookupArtifact"
              />
              <UButton
                size="sm"
                color="neutral"
                variant="outline"
                icon="i-lucide-arrow-right"
                label="Open"
                :disabled="!lookupValid"
                block
                @click="lookupArtifact"
              />
              <p
                v-if="lookupId && !lookupValid"
                class="text-xs text-muted"
              >
                Enter a valid uuid to open.
              </p>
            </div>
          </template>
        </UAccordion>
      </div>

      <!-- Detail view -->
      <div class="space-y-3">
        <UAlert
          v-if="detailError"
          color="error"
          variant="soft"
          icon="i-lucide-circle-alert"
          title="Unable to load artifact"
          :description="detailError"
        />

        <div
          v-if="!selectedId && !detailPending"
          class="rounded-lg border border-dashed border-default bg-default/60 p-10 text-center"
        >
          <UIcon name="i-lucide-file-text" class="mx-auto size-8 text-muted" />
          <p class="mt-3 text-sm text-muted">
            Select a recent artifact or open one by id.
          </p>
        </div>

        <div
          v-else-if="detailPending"
          class="flex items-center gap-2 rounded-lg border border-default bg-default/60 p-6 text-sm text-muted"
        >
          <UIcon name="i-lucide-loader-circle" class="size-4 animate-spin" />
          Loading artifact…
        </div>

        <UCard
          v-else-if="detail"
          :ui="{ root: 'bg-default/60', body: 'space-y-4' }"
        >
          <div class="flex flex-wrap items-start justify-between gap-3">
            <div class="min-w-0">
              <h3 class="truncate text-base font-semibold text-highlighted">
                {{ detail.metadata.title }}
              </h3>
              <p class="mt-1 truncate font-mono text-xs text-muted">
                {{ detail.metadata.id }}
              </p>
            </div>
            <div class="flex items-center gap-2">
              <UBadge color="primary" variant="soft">
                {{ detail.metadata.type }}
              </UBadge>
              <UButton
                v-if="isReport"
                size="xs"
                color="neutral"
                variant="outline"
                icon="i-lucide-external-link"
                label="Open standalone"
                :to="`/artifacts/${detail.metadata.id}`"
                target="_blank"
              />
            </div>
          </div>

          <div class="grid gap-3 sm:grid-cols-2">
            <div>
              <p class="text-xs font-medium uppercase tracking-wide text-muted">
                Dataset id
              </p>
              <p class="mt-1 truncate font-mono text-xs text-highlighted">
                {{ detail.metadata.datasetId || '—' }}
              </p>
            </div>
            <div>
              <p class="text-xs font-medium uppercase tracking-wide text-muted">
                Type
              </p>
              <p class="mt-1 text-sm text-highlighted">
                {{ detail.metadata.type }}
              </p>
            </div>
            <div>
              <p class="text-xs font-medium uppercase tracking-wide text-muted">
                Created
              </p>
              <p class="mt-1 text-sm text-highlighted">
                {{ formatDate(detail.metadata.createdAt) }}
              </p>
            </div>
            <div>
              <p class="text-xs font-medium uppercase tracking-wide text-muted">
                Updated
              </p>
              <p class="mt-1 text-sm text-highlighted">
                {{ formatDate(detail.metadata.updatedAt) }}
              </p>
            </div>
          </div>

          <div v-if="isReport" class="space-y-2">
            <div class="flex items-center justify-between">
              <p class="text-xs font-medium uppercase tracking-wide text-muted">
                Report preview
              </p>
              <UBadge
                v-if="detail.report?.truncated"
                color="warning"
                variant="soft"
              >
                Truncated
              </UBadge>
            </div>
            <div class="max-h-[28rem] overflow-auto rounded-md border border-default bg-elevated/40 p-4">
              <ChatComark
                v-if="reportContent"
                :markdown="reportContent"
                class="max-w-none text-sm leading-6"
              />
              <p v-else class="text-sm text-muted">
                Report content is empty.
              </p>
            </div>
          </div>

          <div
            v-else
            class="rounded-md border border-default bg-elevated/40 p-3 text-sm text-muted"
          >
            <UIcon name="i-lucide-info" class="mr-1 inline size-4 align-text-bottom" />
            This artifact type does not have a chat-safe preview.
          </div>

          <DevtoolsJson
            title="Raw response"
            :value="detail"
            collapsed
          />
        </UCard>
      </div>
    </div>
  </div>
</template>
